###create new cart when user register
POST http://localhost:4000/cart/
Content-Type: application/json

{
  "userId": "61a0b118c4b5a4c7f34aa251",
  "products": []
}

###get user cart
GET http://localhost:4000/cart/61a0b118c4b5a4c7f34aa251
Content-Type: application/json


###update cart
PUT http://localhost:4000/cart/61a0b1eeeb67770feee9c343
Content-Type: application/json

{
  "products": [
    {
      "productId": "6197a218b06fbecd7ad08c3a"
    },
    {
      "productId": "619b983a89c63088d5eb9d90"
    }
  ]
}

###delete user cart
DELETE http://localhost:4000/cart/61a0b118c4b5a4c7f34aa251
Content-Type: application/json


#############################################################################################################################


###create new order
POST http://localhost:4000/orders/
Content-Type: application/json

{
  "userId": "61a0b118c4b5a4c7f34aa251",
  "userName": "Công Phượng",
  "products": [
    {
      "productId": "6197a218b06fbecd7ad08c3a",
      "price": 220000,
      "quantity": 1
    }
  ],
  "amount": 1,
  "totalPrice": 220000,
  "address": "14 Nguyễn Trãi, Hải Châu, Đà Nẵng",
  "phone": "036157894"
}

###get all order for admin
GET http://localhost:4000/dashboard/orders/
Content-Type: application/json


###get all user order 
GET http://localhost:4000/orders/61a0f1e672ae3cb7669f4919
Content-Type: application/json


###change status order
PUT http://localhost:4000/dashboard/orders/61a0f7bb94310ba296c7b31a
Content-Type: application/json

{
  "status": "canceled" 
}


#############################################################################################################################


### create new user
POST http://localhost:4000/auth/register 
Content-Type: application/json

{
  "username": "tuananh",
  "name": "Tuấn Anh",
  "phone": "036157894",
  "address": "14 Nguyễn Trãi, Hải Châu, Đà Nẵng",
  "password": "123456"
}

### user login
POST  http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "tuananh",
  "password": "123456"
}

###Delete user
DELETE http://localhost:4000/auth/delete/619685aadccb883f3474bcd8
Content-Type: application/json


#############################################################################################################################


###
PUT http://localhost:4000/auth/update/619d3c15933c0d61da52e4ac
Content-Type: application/json

{
  "cart": [
    {
      "productId": "61990aafa51279f060cc997b",
      "productImage": "abc",
      "productName": "san pham 1152",
      "productPrice": 310000,
      "productDiscount": 12,
      "quantity": 1
    },
    {
      "productId": "6197a218b06fbecd7ad08c3a",
      "productImage": "abc",
      "productName": "Tam quoc",
      "productPrice": 310000,
      "productDiscount": 12,
      "quantity": 5
    },
    {
      "productId": "619b983a89c63088d5eb9d90",
      "productImage": "abc",
      "productName": "Tay du ky",
      "productPrice": 310000,
      "productDiscount": 12,
      "quantity": 2
    }   
  ]
}

### 
POST http://localhost:4000/dashboard/products/post
Content-Type: application/json

{
  "name": "Thuỷ Hử",
  "image": "https://bitly.com.vn/z6p4w6",
  "price": 320000,
  "oldPrice": 400000,
  "discount": 20,
  "description": "Tam quốc diễn nghĩa của La Quán Trung là một trong những kiệt tác của văn học thế giới. Ngay từ khi được dịch sang chữ quốc ngữ vào đầu thế kỷ XX, tiểu thuyết này đã được bạn đọc Việt Nam đón nhận nồng nhiệt; từ đó đến nay có vô vàn ấn bản Tam quốc ra đời, mỗi ấn bản lại mang một màu sắc khác nhau. Để có thêm sự lựa chọn cho bạn đọc, Đông A ra mắt bản Tam quốc diễn nghĩa 2 tập bìa cứng.",
  "author": "La Quán Trung",
  "nhaXB": "NXB Văn Học",
  "namXB": "2020",
  "soTrang": "1892",
  "rating": 0,
  "category": "Văn Học"
}

###
PUT http://localhost:4000/dashboard/products/update/61990aafa51279f060cc997b
Content-Type: application/json

{
  "name": "Thuỷ Hử",
  "image": "https://cdn0.fahasa.com/media/catalog/product/cache/1/small_image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/m/image_244718_1_4729.jpg",
  "price": 254200,
  "oldPrice": 310000,
  "discount": 18,
  "description": "Thủy Hử là một áng văn chương tuyệt bút, được coi là một trong tứ đại danh tác của văn học cổ điển Trung Hoa. Trải qua sáu trăm năm thăng trầm của lịch sử, nhiều triều đại bị thay thế, nhiều biến cố đã xảy ra, biết bao vật đổi sao dời… Nhưng Thủy Hử của Thi Nại Am vẫn đi vào lòng người của biết bao thế hệ độc giả đến từ khắp nơi trên thế giới. Câu chuyện về một trăm lẻ tám người anh hùng nơi bến nước cùng tụ tập vì đại nghĩa, cùng quyết chí bền gan làm nên sự nghiệp lớn đã truyền cảm hứng cho rất nhiều loại hình nghệ thuật khác làm nên những tác phẩm để đời.",
  "author": "Thi Nại Am",
  "nhaXB": "NXB Văn Học",
  "namXB": "2018",
  "soTrang": "1204",
  "category": "Văn Học"
}

###Get product by category
GET http://localhost:4000/dashboard/get?category=lap-trinh
Content-Type: application/json


###Find product by Id
GET http://localhost:4000/dashboard/product/619b983a89c63088d5eb9d90
Content-Type: application/json

###https://bookstore360.herokuapp.com/
